# Generated by Django 5.0.6 on 2026-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_volunteers_needed_assigned_volunteers'),
        ('volunteers', '0002_add_skill_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='volunteers.skill'),
        ),
    ]
