# Generated by Django 5.0.6 on 2026-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('transport', 'Transport'), ('physical', 'Physical'), ('practical', 'Practical'), ('technical', 'Technical'), ('social', 'Social'), ('language', 'Language')], max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.skill'),
        ),
    ]
